import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '#/styles/Home.module.css'
import useSWR from 'swr'
import { Post } from '@prisma/client'
import { useRouter } from 'next/router'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const supabase = useSupabaseClient()
    const router = useRouter()
    const handleSignUp = async () => {
        const { data: { user } } = await supabase.auth.signUp({
            email,
            password,
            options: {
                emailRedirectTo: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/dashboard`,
            },
        })
        router.reload()
    }

    const handleSignIn = async () => {
        const { data: { user } } = await supabase.auth.signInWithPassword({
            email,
            password,
        })
        if (user) {
            router.replace(router.query.redirectedFrom as string | undefined || '/dashboard')
        } else {
            router.reload()
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <input name="email" onChange={(e) => setEmail(e.target.value)} value={email} />
                <input
                    type="password"
                    name="password"
                    onChange={(e) => setPassword(e.target.value)}
                    value={password}
                />
                <button onClick={handleSignUp}>Sign up</button>
                <button onClick={handleSignIn}>Sign in</button>
            </main>
        </>
    )
}
