import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '#/styles/Home.module.css'
import useSWR from 'swr'
import { Post } from '@prisma/client'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: posts } = useSWR('key', async () => {
    const posts: Post[] = await (await fetch('/api/posts')).json();
    return posts
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {posts?.map(({ id, title }) =>
          <div key={id}>{title}</div>
        )}
      </main>
    </>
  )
}
